### ISSUE TITLE
deprecated warn argument to command module since ansible 2.14

### ISSUE THREAD

**Issue by jability** [OndrejHome/ansible.ha-cluster-pacemaker#25]
Hello,

**Issue**
Since Ansible 2.14, the module `ansible.builtin.command` doesn't have a `warn` argument anymore.
As such, this role is currently failing on CentOS, RHEL, AlmaLinux and RockyLinux.

**Comment by OndrejHome** [comment]
Thank you again Julien for the PR that fixes this issue! 
The changes are now part of `master` branch and there is also new tagged version `35.0.0` that can be used to get latest version of role (also pushed to ansible galaxy).
