### ISSUE TITLE
Service pcs-ruby not started on Debian 11

### ISSUE THREAD

**Issue by jbe-dw** [OndrejHome/ansible.ha-cluster-pacemaker#28]
Hello,

When installing pacemaker on Debian, pcsd rely on "pcsd-ruby" service which is not started at install (but the unit is enabled by default). The authentication fails. After manually starting the service on each node everything is fine.

Is it possible to make it start in the role ?
Thank you

**Comment by OndrejHome** [comment]
Hello @jbe-dw ,

Thank you for using the ha-cluster-pacemaker role and for taking time to report this issue.
I had a look at this and at first I have not experienced the issue on Debian 11.7. However it looks like the problem appears only if the pcs package was already installed and pcsd-ruby service was stopped for whatever reason - at that time the role fails as you have reported. The `pcsd-ruby` service seems to be specific only to Debian 11.x packaging of pcs and I have added change to role to explicitly start and enable the `pcsd-ruby` service. 

In-short: Issue doesn't seems to affect fresh installs where `pcs` package is installed by role, but affect systems where `pcs` was already installed and stopped in past. Issue is specific to Debian 11.x (Debian 10.x is not affected as there is no `pcsd-ruby` service)

The change to role is now in `master` branch and if you would be able to give it a test please let me know if this changed version of role works well for you.

Thank you!

**Comment by jbe-dw** [comment]
Thank you I'll give a try in the week.

**Comment by jbe-dw** [comment]
It works perfectly, thank you

**Comment by OndrejHome** [comment]
Thank you for the confirmation and your time to test the change!
I will close this issue now as the change is now present in `master` and tagged in recent release.
