### ISSUE TITLE
Attempts to load nonexistent Centos 8 Stream variables

### ISSUE THREAD

**Issue by jackhodgkiss** [OndrejHome/ansible.ha-cluster-pacemaker#34]
When targeting Centos 8 Stream systems the role will fail on `Include distribution version specific variables` with the following error message `No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found`.

When looking at the value of `ansible_distribution_file_variety` and `ansible_distribution` it is clear that it is now attempting to load `vars/centos8.yml` which doesn't exist. Fortunately, copying the contents of `vars/redhat8.yml` to `vars/centos8.yml` works and resolves the issue.

**Comment by OndrejHome** [comment]
Hello @jackhodgkiss ,

Thank you for using the role and opening this issue and accompanied PR! 
I have not looked at CentOS Stream for quite a time, so I have just now tested on my system and yes indeed same issue happens for me. My guess why this could be the case is that original CentOS non-stream is more looking like RHEL so the `redhat` has matched there while the stream at time probably did the same. Same content as `vars/redhat8.yml` makes sense here and should work unless some names changed.

Would you please let me know the output from `ansible --version` that you use on your system?

I have tested that same behaviour happens on following version.
~~~
# ansible --version
ansible [core 2.16.2]
...
  python version = 3.11.7 (main, Dec 28 2023, 20:03:36) [GCC 13.2.1 20230826] (/usr/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
~~~

And when trying to get information about distribution from CentOS 8.5 and CentOS 8 Stream I get following data from 'setup' module. (this is mostly for my tracking purposes)
~~~
        "ansible_distribution": "CentOS",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/centos-release",
        "ansible_distribution_file_variety": "CentOS",
        "ansible_distribution_major_version": "8",
        "ansible_distribution_release": "Stream",
        "ansible_distribution_version": "8",
~~~
~~~
        "ansible_distribution": "CentOS",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/redhat-release",
        "ansible_distribution_file_variety": "RedHat",
        "ansible_distribution_major_version": "8",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "8.5",
~~~

I will try to have look at this either this weekend or during next week. Thank you!

**Comment by jackhodgkiss** [comment]
Hello @OndrejHome as requested here is the output of `ansible --version`

```
ansible [core 2.11.12]
  config file = None
  configured module search path = ['/home/cloud-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cloud-user/staging/venvs/kayobe/lib/python3.6/site-packages/ansible
  ansible collection location = /home/cloud-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cloud-user/staging/venvs/kayobe/bin/ansible
  python version = 3.6.8 (default, Jan 25 2023, 15:03:30) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
  jinja version = 3.0.3
  libyaml = True
```

Also can confirm that the output of `ansible.builtin.setup` is identical to what you have posted for Centos 8 Stream.

**Comment by OndrejHome** [comment]
Thank you Jack (@jackhodgkiss ) for the outputs,,

confirming my suspicion the ansible version 2.11 was first that started referring to CentOS Stream as "CentOS' instead of 'Redhat', luckily the CentOS Linux is still identified same for whole time. So it makes sense to add a new file for CentOS stream. I will be merging your PR in upcoming days together with few adjustments to documentation so it is clear what is current state.
Once again, Thank you for bringing this issue up!

I will update this issue and PR within few days.

**Comment by OndrejHome** [comment]
Thank you once again @jackhodgkiss  for your time and provided PR! 
The changes are now merged in `master` along with documentation update and also with addition of CentOS 9 Stream just in case that it was needed.
