### ISSUE TITLE
enable PCS GUI

### ISSUE THREAD

**Issue by frank3427** [OndrejHome/ansible.ha-cluster-pacemaker#4]
to enable the GUI
vi /etc/sysconfig/pcsd

change PCSD_DISABLE_GUI=true to PCSD_DISABLE_GUI=false

service pcsd restart
you should now be able to get to the GUI vi https://(host or dns):2224
you will also need to open iptables top new port
iptables -I INPUT -p tcp --dport 2224 -m state --state NEW,ESTABLISHED -j ACCEPT

this only needs to be done on one host to manage the cluster vi the GUI

**Comment by OndrejHome** [comment]
Hi @frank3427,
Looking at the my testing configuration in CentOS 7.4 the PCSD is enabled by default. Port `2224/tcp` should also be opened as it is used for node authorisation (if `cluster_firewal: true` is used with role, which is default if not specified). Currently the role is not checking if the `PCSD_DISABLE_GUI=false` is configured in the `/etc/sysconfig/pcsd`.

Could you please let me know on which system you have encountered this?

**Comment by frank3427** [comment]
by default in centos 6.9 PCSD_DISABLE_GUI=true, the gui is disabled

**Comment by OndrejHome** [comment]
It is interesting that defaults for CentOS/RHEL 6.X are different from CentOS/RHEL 7.X. I have created option that can be used to enable/disable PCSD web GUI. If option is not used then role will not change that option. Change is currently in 'develop' branch. Please let me know if there are any issues with it. I will include it in 'master' in next version. 
Thank you for reporting this interesting default!

**Comment by frank3427** [comment]
I have done some testing and and the gui is now enabled, I have only tested with centOS6.9

**Comment by OndrejHome** [comment]
I have merged the changes into 'master', the changes are now available from version 'v15' of 'OndrejHome.ha-cluster-pacemaker' role. I will now close this Issue, if there is some problem with this feel free to re-open this one or create a new one.

 Thank you for the suggestion on feature and for testing!
